In [1]:
import pandas as pd 
import plotly.express as px
import plotly.graph_objects as go
import json

In [2]:
path = "/Users/emanieluu/Documents/Projet_Python_2A/"

file1 = "ID_2019r.csv"
file_cap2019 = "capact_tot0019.csv"
file2 = "communes-20190101.json"
file3 = "a-dep2021.json"
# Opening JSON file
f = open(path + file2)
f2 = open(path + file3)
communes = json.load(f)
departements = json.load(f2)

In [3]:
df_cap2019 = pd.read_csv(path + file_cap2019,sep = ";", encoding = "ISO-8859-1",low_memory=False)
df_cap2019.head()

,fi,an,fi_ej,rs,stj,cat,dep,reg,anc_reg,espic,...,LIT,SEJHC,JOU,PLA,SEJHP,PAS,SEJACC,SEHEM,SERAD,SECHI
0,010000495,2005,010783009,C.P.A. BOURG EN BRESSE,61.0,292.0,01,84.0,82.0,NaN,...,424.0,4283.0,145112.0,109.0,20943.0,NaN,NaN,NaN,NaN,NaN
1,010000495,2010,010783009,C.P.A. BOURG EN BRESSE,61.0,292.0,01,84.0,82.0,NaN,...,409.0,6781.0,135981.0,124.0,42635.0,NaN,NaN,NaN,NaN,NaN
2,010000495,2011,010783009,C.P.A. BOURG EN BRESSE,61.0,292.0,01,84.0,82.0,NaN,...,386.0,6327.0,134649.0,124.0,18518.0,NaN,NaN,NaN,NaN,NaN
3,010000495,2012,010783009,C.P.A. BOURG EN BRESSE,61.0,292.0,01,84.0,82.0,6.0,...,386.0,6021.0,134222.0,124.0,18875.0,NaN,NaN,NaN,NaN,NaN
4,010000495,2013,010783009,C.P.A. BOURG EN BRESSE,61.0,292.0,01,84.0,82.0,6.0,...,371.0,6463.0,131801.0,124.0,17576.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df_cap2019_2 = df_cap2019[df_cap2019["an"] == 2019]
cap_par_dep = df_cap2019_2.groupby(["dep"]).sum()["LIT"].to_frame().reset_index()

In [10]:
fig = px.choropleth_mapbox(
    cap_par_dep,
    geojson= departements,
    locations='dep',
    featureidkey="properties.dep", #open-street-map
    color= cap_par_dep['LIT'],
    color_continuous_scale='YlOrRd',
    range_color=(0, max(cap_par_dep["LIT"])),
    hover_name='LIT',
    hover_data =['dep'],
    mapbox_style='open-street-map',
    zoom=4,
    center={'lat': 47, 'lon': 2},
    opacity=0.8,
    title = "Nombre de lits d'hopitalisation par départements en 2019"
   )

# fig.show()

In [6]:
file_pm = "pm_01_19.csv"
df_pm = pd.read_csv(path + file_pm, sep = ";", encoding = "ISO-8859-1",low_memory=False)
df_pm2019 = df_pm[df_pm["an"] == 2019]
df_pm2 = df_pm2019.groupby(["dep"]).sum()["ETPSAL"].to_frame().reset_index()
df_pm2.head()

  dep  ETPSAL
0  01  373.63
1  02  635.11
2  03  406.68
3  04  160.39
4  05  303.90

In [9]:
fig = px.choropleth_mapbox(
    df_pm2,
    geojson= departements,
    locations='dep',
    featureidkey="properties.dep", #open-street-map
    color= df_pm2['ETPSAL'],
    color_continuous_scale='YlOrRd',
    range_color=(0, max(df_pm2['ETPSAL'])),
    hover_name='ETPSAL',
    hover_data =['dep'],
    mapbox_style='open-street-map',
    zoom=4,
    center={'lat': 47, 'lon': 2},
    opacity=0.8,
    title = " Nombre d'ETP salariés (hors médico-social) par département en 2019 "
   )

# fig.show()